name: Quran Reels Auto Publisher

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: سحب الملفات
      uses: actions/checkout@v3

    - name: تجهيز لغة بايثون
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: تثبيت مكتبات المونتاج الأساسية
      run: |
        sudo apt-get update
        sudo apt-get install ffmpeg imagemagick --no-install-recommends -y
        sudo sed -i 's/none/read,write/g' /etc/ImageMagick-6/policy.xml

    - name: تثبيت مكتبات بايثون وأسلحة التخفي
      run: |
        pip install -r requirements.txt
        pip install -U --pre yt-dlp curl-cffi

    - name: تشغيل استوديو المونتاج والنشر
      env:
        PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        IG_USERNAME: ${{ secrets.IG_USERNAME }}
        IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        ERROR_BOT_TOKEN: ${{ secrets.ERROR_BOT_TOKEN }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        YOUTUBE_COOKIES: ${{ secrets.YOUTUBE_COOKIES }}
      run: python bot.py

    - name: حفظ الذاكرة وجلسة إنستجرام الآمنة
      run: |
        git config --global user.name "QuranBot"
        git config --global user.email "bot@example.com"
        git add history.json
        # هذا السطر الذكي يرفع الجلسة فقط إذا تم إنشاؤها بنجاح
        if [ -f session.json ]; then git add session.json; fi
        git commit -m "تحديث الذاكرة وحفظ جلسة إنستجرام" || echo "لا يوجد تحديث جديد"
        git push
